# This file is generated by rules_pycross.
# It is not intended for manual editing.
"""Pycross-generated dependency targets."""

load("@@rules_pycross+//pycross:defs.bzl", "pycross_wheel_library", "pypi_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

PINS = {
    "certifi": "certifi@2025.8.3",
    "charset-normalizer": "charset-normalizer@3.4.3",
    "idna": "idna@3.10",
    "numpy": "numpy@2.2.6",
    "pandas": "pandas@2.3.2",
    "python-dateutil": "python-dateutil@2.9.0.post0",
    "pytz": "pytz@2025.2",
    "requests": "requests@2.32.5",
    "six": "six@1.17.0",
    "tzdata": "tzdata@2025.2",
    "urllib3": "urllib3@2.5.0",
}

# buildifier: disable=unnamed-macro
def targets():
    """Generated package targets."""

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.alias(
        name = "_env_python_3.10.11_aarch64-apple-darwin",
        actual = "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_aarch64-apple-darwin_config",
    )

    native.alias(
        name = "_env_python_3.10.11_aarch64-unknown-linux-gnu",
        actual = "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_aarch64-unknown-linux-gnu_config",
    )

    native.alias(
        name = "_env_python_3.10.11_x86_64-unknown-linux-gnu",
        actual = "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_x86_64-unknown-linux-gnu_config",
    )

    # buildifier: disable=unused-variable
    _target = select({
        ":_env_python_3.10.11_aarch64-apple-darwin": "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_aarch64-apple-darwin.json",
        ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_aarch64-unknown-linux-gnu.json",
        ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@@rules_pycross++environments+rules_pycross_e2e_environments//:python_3.10.11_x86_64-unknown-linux-gnu.json",
    })

    native.alias(
        name = "_wheel_certifi@2025.8.3",
        actual = "@poetry_lock_file_wheel_certifi_2025.8.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "certifi@2025.8.3",
        wheel = ":_wheel_certifi@2025.8.3",
    )

    native.alias(
        name = "_wheel_charset-normalizer@3.4.3",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_macosx_10_9_universal2//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "charset-normalizer@3.4.3",
        wheel = ":_wheel_charset-normalizer@3.4.3",
    )

    native.alias(
        name = "_wheel_idna@3.10",
        actual = "@poetry_lock_file_wheel_idna_3.10_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "idna@3.10",
        wheel = ":_wheel_idna@3.10",
    )

    native.alias(
        name = "_wheel_numpy@2.2.6",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_macosx_11_0_arm64//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "numpy@2.2.6",
        wheel = ":_wheel_numpy@2.2.6",
    )

    _pandas_2_3_2_deps = [
        ":numpy@2.2.6",
        ":python-dateutil@2.9.0.post0",
        ":pytz@2025.2",
        ":tzdata@2025.2",
    ]

    native.alias(
        name = "_wheel_pandas@2.3.2",
        actual = select({
            ":_env_python_3.10.11_aarch64-apple-darwin": "@poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_macosx_11_0_arm64//file",
            ":_env_python_3.10.11_aarch64-unknown-linux-gnu": "@poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64//file",
            ":_env_python_3.10.11_x86_64-unknown-linux-gnu": "@poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "pandas@2.3.2",
        deps = _pandas_2_3_2_deps,
        wheel = ":_wheel_pandas@2.3.2",
    )

    _python_dateutil_2_9_0_post0_deps = [
        ":six@1.17.0",
    ]

    native.alias(
        name = "_wheel_python-dateutil@2.9.0.post0",
        actual = "@poetry_lock_file_wheel_python_dateutil_2.9.0.post0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "python-dateutil@2.9.0.post0",
        deps = _python_dateutil_2_9_0_post0_deps,
        wheel = ":_wheel_python-dateutil@2.9.0.post0",
    )

    native.alias(
        name = "_wheel_pytz@2025.2",
        actual = "@poetry_lock_file_wheel_pytz_2025.2_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pytz@2025.2",
        wheel = ":_wheel_pytz@2025.2",
    )

    _requests_2_32_5_deps = [
        ":certifi@2025.8.3",
        ":charset-normalizer@3.4.3",
        ":idna@3.10",
        ":urllib3@2.5.0",
    ]

    native.alias(
        name = "_wheel_requests@2.32.5",
        actual = "@poetry_lock_file_wheel_requests_2.32.5_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "requests@2.32.5",
        deps = _requests_2_32_5_deps,
        wheel = ":_wheel_requests@2.32.5",
    )

    native.alias(
        name = "_wheel_six@1.17.0",
        actual = "@poetry_lock_file_wheel_six_1.17.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "six@1.17.0",
        wheel = ":_wheel_six@1.17.0",
    )

    native.alias(
        name = "_wheel_tzdata@2025.2",
        actual = "@poetry_lock_file_wheel_tzdata_2025.2_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tzdata@2025.2",
        wheel = ":_wheel_tzdata@2025.2",
    )

    native.alias(
        name = "_wheel_urllib3@2.5.0",
        actual = "@poetry_lock_file_wheel_urllib3_2.5.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "urllib3@2.5.0",
        wheel = ":_wheel_urllib3@2.5.0",
    )

# buildifier: disable=unnamed-macro
def repositories():
    """Generated package repositories."""

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_certifi_2025.8.3_py3_none_any",
        package_name = "certifi",
        package_version = "2025.8.3",
        filename = "certifi-2025.8.3-py3-none-any.whl",
        sha256 = "f6c12493cfb1b06ba2ff328595af9350c65d6644968e5d3a2ffd78699af217a5",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_macosx_10_9_universal2",
        package_name = "charset-normalizer",
        package_version = "3.4.3",
        filename = "charset_normalizer-3.4.3-cp310-cp310-macosx_10_9_universal2.whl",
        sha256 = "fb7f67a1bfa6e40b438170ebdc8158b78dc465a5a67b6dde178a46987b244a72",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64",
        package_name = "charset-normalizer",
        package_version = "3.4.3",
        filename = "charset_normalizer-3.4.3-cp310-cp310-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl",
        sha256 = "cc9370a2da1ac13f0153780040f465839e6cccb4a1e44810124b4e22483c93fe",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_charset_normalizer_3.4.3_cp310_cp310_manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64",
        package_name = "charset-normalizer",
        package_version = "3.4.3",
        filename = "charset_normalizer-3.4.3-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
        sha256 = "d0e909868420b7049dafd3a31d45125b31143eec59235311fc4c57ea26a4acd2",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_idna_3.10_py3_none_any",
        package_name = "idna",
        package_version = "3.10",
        filename = "idna-3.10-py3-none-any.whl",
        sha256 = "946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_macosx_11_0_arm64",
        package_name = "numpy",
        package_version = "2.2.6",
        filename = "numpy-2.2.6-cp310-cp310-macosx_11_0_arm64.whl",
        sha256 = "8e41fd67c52b86603a91c1a505ebaef50b3314de0213461c7a6e99c9a3beff90",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "numpy",
        package_version = "2.2.6",
        filename = "numpy-2.2.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "efd28d4e9cd7d7a8d39074a4d44c63eda73401580c5c76acda2ce969e0a38e83",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_numpy_2.2.6_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "numpy",
        package_version = "2.2.6",
        filename = "numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "fc7b73d02efb0e18c000e9ad8b83480dfcd5dfd11065997ed4c6747470ae8915",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_macosx_11_0_arm64",
        package_name = "pandas",
        package_version = "2.3.2",
        filename = "pandas-2.3.2-cp310-cp310-macosx_11_0_arm64.whl",
        sha256 = "220cc5c35ffaa764dd5bb17cf42df283b5cb7fdf49e10a7b053a06c9cb48ee2b",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_manylinux_2_17_aarch64.manylinux2014_aarch64",
        package_name = "pandas",
        package_version = "2.3.2",
        filename = "pandas-2.3.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
        sha256 = "42c05e15111221384019897df20c6fe893b2f697d03c811ee67ec9e0bb5a3424",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_pandas_2.3.2_cp310_cp310_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "pandas",
        package_version = "2.3.2",
        filename = "pandas-2.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "cc03acc273c5515ab69f898df99d9d4f12c4d70dbfc24c3acc6203751d0804cf",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_python_dateutil_2.9.0.post0_py2.py3_none_any",
        package_name = "python-dateutil",
        package_version = "2.9.0.post0",
        filename = "python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
        sha256 = "a8b2bc7bffae282281c8140a97d3aa9c14da0b136dfe83f850eea9a5f7470427",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_pytz_2025.2_py2.py3_none_any",
        package_name = "pytz",
        package_version = "2025.2",
        filename = "pytz-2025.2-py2.py3-none-any.whl",
        sha256 = "5ddf76296dd8c44c26eb8f4b6f35488f3ccbf6fbbd7adee0b7262d43f0ec2f00",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_requests_2.32.5_py3_none_any",
        package_name = "requests",
        package_version = "2.32.5",
        filename = "requests-2.32.5-py3-none-any.whl",
        sha256 = "2462f94637a34fd532264295e186976db0f5d453d1cdd31473c85a6a161affb6",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_six_1.17.0_py2.py3_none_any",
        package_name = "six",
        package_version = "1.17.0",
        filename = "six-1.17.0-py2.py3-none-any.whl",
        sha256 = "4721f391ed90541fddacab5acf947aa0d3dc7d27b2e1e8eda2be8970586c3274",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_tzdata_2025.2_py2.py3_none_any",
        package_name = "tzdata",
        package_version = "2025.2",
        filename = "tzdata-2025.2-py2.py3-none-any.whl",
        sha256 = "1a403fada01ff9221ca8044d701868fa132215d84beb92242d9acd2147f667a8",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_file_wheel_urllib3_2.5.0_py3_none_any",
        package_name = "urllib3",
        package_version = "2.5.0",
        filename = "urllib3-2.5.0-py3-none-any.whl",
        sha256 = "e6b01673c0fa6a13e374b50871808eb3bf7046c4b125b216f6bf1cc604cff0dc",
    )
