load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "pymodule",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@poetry_lock_file//deps:numpy",
        "@poetry_lock_file//deps:pandas",
    ],
)

py_test(
    name = "pymodule_test",
    srcs = ["__test__.py"],
    main = "__test__.py",
    deps = [
        "@poetry_lock_file//deps:numpy",
        "@poetry_lock_file//deps:pandas",
    ],
)
